import Link from "next/link";
import "./global.css";



export const metadata = {
  title: "Bibliotheque Municipale",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    
  );
}
